# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crank_pb2 as crank__pb2


class CrankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCrank = channel.unary_unary(
                '/bicycle.Crank/CreateCrank',
                request_serializer=crank__pb2.CreateCrankRequest.SerializeToString,
                response_deserializer=crank__pb2.CreateCrankResponse.FromString,
                )


class CrankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCrank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCrank': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCrank,
                    request_deserializer=crank__pb2.CreateCrankRequest.FromString,
                    response_serializer=crank__pb2.CreateCrankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bicycle.Crank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Crank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCrank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bicycle.Crank/CreateCrank',
            crank__pb2.CreateCrankRequest.SerializeToString,
            crank__pb2.CreateCrankResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
