# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crank.proto',
  package='bicycle',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63rank.proto\x12\x07\x62icycle\"_\n\x12\x43reateCrankRequest\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x12\n\narm_length\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\"8\n\x13\x43reateCrankResponse\x12!\n\x05\x63rank\x18\x01 \x01(\x0b\x32\x12.bicycle.BikeCrank\"b\n\tBikeCrank\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\x12\x12\n\narm_length\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t2Q\n\x05\x43rank\x12H\n\x0b\x43reateCrank\x12\x1b.bicycle.CreateCrankRequest\x1a\x1c.bicycle.CreateCrankResponseb\x06proto3'
)




_CREATECRANKREQUEST = _descriptor.Descriptor(
  name='CreateCrankRequest',
  full_name='bicycle.CreateCrankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='bicycle.CreateCrankRequest.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='bicycle.CreateCrankRequest.manufacturer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arm_length', full_name='bicycle.CreateCrankRequest.arm_length', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='bicycle.CreateCrankRequest.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=119,
)


_CREATECRANKRESPONSE = _descriptor.Descriptor(
  name='CreateCrankResponse',
  full_name='bicycle.CreateCrankResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crank', full_name='bicycle.CreateCrankResponse.crank', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=177,
)


_BIKECRANK = _descriptor.Descriptor(
  name='BikeCrank',
  full_name='bicycle.BikeCrank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bicycle.BikeCrank.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='bicycle.BikeCrank.frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='bicycle.BikeCrank.manufacturer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arm_length', full_name='bicycle.BikeCrank.arm_length', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='bicycle.BikeCrank.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=277,
)

_CREATECRANKRESPONSE.fields_by_name['crank'].message_type = _BIKECRANK
DESCRIPTOR.message_types_by_name['CreateCrankRequest'] = _CREATECRANKREQUEST
DESCRIPTOR.message_types_by_name['CreateCrankResponse'] = _CREATECRANKRESPONSE
DESCRIPTOR.message_types_by_name['BikeCrank'] = _BIKECRANK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateCrankRequest = _reflection.GeneratedProtocolMessageType('CreateCrankRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECRANKREQUEST,
  '__module__' : 'crank_pb2'
  # @@protoc_insertion_point(class_scope:bicycle.CreateCrankRequest)
  })
_sym_db.RegisterMessage(CreateCrankRequest)

CreateCrankResponse = _reflection.GeneratedProtocolMessageType('CreateCrankResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECRANKRESPONSE,
  '__module__' : 'crank_pb2'
  # @@protoc_insertion_point(class_scope:bicycle.CreateCrankResponse)
  })
_sym_db.RegisterMessage(CreateCrankResponse)

BikeCrank = _reflection.GeneratedProtocolMessageType('BikeCrank', (_message.Message,), {
  'DESCRIPTOR' : _BIKECRANK,
  '__module__' : 'crank_pb2'
  # @@protoc_insertion_point(class_scope:bicycle.BikeCrank)
  })
_sym_db.RegisterMessage(BikeCrank)



_CRANK = _descriptor.ServiceDescriptor(
  name='Crank',
  full_name='bicycle.Crank',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=279,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCrank',
    full_name='bicycle.Crank.CreateCrank',
    index=0,
    containing_service=None,
    input_type=_CREATECRANKREQUEST,
    output_type=_CREATECRANKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRANK)

DESCRIPTOR.services_by_name['Crank'] = _CRANK

# @@protoc_insertion_point(module_scope)
